### ISSUE TITLE
A link with localhost

### ISSUE THREAD

**Issue by Omnia89** [treeman/jonashietala#12]
https://github.com/treeman/jonashietala/blob/4dfd8664e8564c4a9da503ed6295b26eec2005c4/posts/2024-11-26-the_current_cybershard_layout.dj#L344

Hi there, I love your blog! I noticed that by mistake the first link of the page points to `localhost’.

I didn’t know how to report it and so I opened an issue.

Keep going

**Comment by treeman** [comment]
Thank you, appreciate it! Fixed.
