### ISSUE TITLE
Does the server  has to be restarted whenever a new post is created?

### ISSUE THREAD

**Issue by naddika** [treeman/jonashietala#3]
Does the server  has to be restarted whenever a new post is created?

There's no way to generate a new post such that the server, whist running, will find it in `/posts` directory and display it?

**Comment by treeman** [comment]
Hey, sorry about that. There are a bunch of reload related things I never bothered to add.

But I just pushed a change that should add posts while running. I need to add the same for `drafts` and moving a draft to a post and some other things too though at some other time.

Thanks for asking about it!
